---

- name: create horizon mount directory
  file:
    path: /opt/horizon/volumes/horizon
    state: directory
    mode: 0655

- name: create horizon scripts directory
  file:
    path: /opt/horizon/scripts
    state: directory
    mode: 0655

- name: template upload_horizon_logs script to remote
  template:
    src: scripts/upload_horizon_logs.sh.j2
    dest: /opt/horizon/scripts/upload_horizon_logs.sh
    mode: 0700

- name: template upload_horizon_db script to remote
  template:
    src: scripts/upload_horizon_db.sh.j2
    dest: /opt/horizon/scripts/upload_horizon_db.sh
    mode: 0700

- name: template restart_horizon.sh.js script to remote
  template:
    src: scripts/restart_horizon.sh.j2
    dest: /opt/horizon/scripts/restart_horizon.sh
    mode: 0700

- name: template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/horizon/docker-compose.yml
    mode: 0400
